export const FIREBASE = "FIREBASE";
export const LOADING = "LOADING";
export const LOADING_LISTING_DETAIL = "LOADING_LISTING_DETAIL";
export const LOADING_REVIEW = "LOADING_REVIEW";
export const SCROLL_TO = "SCROLL_TO";
export const REQUEST_TIMEOUT = "REQUEST_TIMEOUT";
export const HOME_REQUEST_TIMEOUT = "HOME_REQUEST_TIMEOUT";
export const ARTICLE_REQUEST_TIMEOUT = "ARTICLE_REQUEST_TIMEOUT";
export const LISTING_REQUEST_TIMEOUT = "LISTING_REQUEST_TIMEOUT";
export const LISTING_SEARCH_REQUEST_TIMEOUT = "LISTING_SEARCH_REQUEST_TIMEOUT";
export const EVENT_SEARCH_REQUEST_TIMEOUT = "EVENT_SEARCH_REQUEST_TIMEOUT";
export const EVENT_REQUEST_TIMEOUT = "EVENT_REQUEST_TIMEOUT";
export const LISTING_DETAIL_DES_REQUEST_TIMEOUT =
  "LISTING_DETAIL_DES_REQUEST_TIMEOUT";
export const LISTING_DETAIL_PHOTOS_REQUEST_TIMEOUT =
  "LISTING_DETAIL_PHOTOS_REQUEST_TIMEOUT";
export const LISTING_DETAIL_VID_REQUEST_TIMEOUT =
  "LISTING_DETAIL_VID_REQUEST_TIMEOUT";
export const LISTING_DETAIL_LIST_REQUEST_TIMEOUT =
  "LISTING_DETAIL_LIST_REQUEST_TIMEOUT";
export const LISTING_DETAIL_REVIEWS_REQUEST_TIMEOUT =
  "LISTING_DETAIL_REVIEWS_REQUEST_TIMEOUT";
export const LISTING_DETAIL_EVENT_REQUEST_TIMEOUT =
  "LISTING_DETAIL_EVENT_REQUEST_TIMEOUT";
export const LISTING_DETAIL_SIDEBAR_REQUEST_TIMEOUT =
  "LISTING_DETAIL_SIDEBAR_REQUEST_TIMEOUT";
export const MENU_REQUEST_TIMEOUT = "MENU_REQUEST_TIMEOUT";

export const NEAR_BY_FOCUS = "NEAR_BY_FOCUS";

export const GET_TAB_NAVIGATOR = "GET_TAB_NAVIGATOR";
export const GET_STACK_NAVIGATOR = "GET_STACK_NAVIGATOR";

export const GET_TRANSLATIONS = "GET_TRANSLATIONS";
export const GET_LISTINGS = "GET_LISTINGS";
export const GET_LISTINGS_LOADMORE = "GET_LISTINGS_LOADMORE";
export const GET_LISTING_SEARCH_RESULTS = "GET_LISTING_SEARCH_RESULTS";
export const GET_LISTING_SEARCH_RESULTS_LOADMORE =
  "GET_LISTING_SEARCH_RESULTS_LOADMORE";
export const GET_LISTING_BY_CAT = "GET_LISTING_BY_CAT";
export const GET_LISTING_BY_CAT_LOADMORE = "GET_LISTING_BY_CAT_LOADMORE";
export const GET_LISTING_NEARBY = "GET_LISTING_NEARBY";
export const GET_HOME_SCREEN = "GET_HOME_SCREEN";
export const GET_LISTING_FILTERS = "GET_LISTING_FILTERS";
export const GET_LOCATION_LIST = "GET_LOCATION_LIST";
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const RESET_SELECTED_CATEGORY_LIST = "RESET_SELECTED_CATEGORY_LIST";
export const RESET_SELECTED_LOCATION_LIST = "RESET_SELECTED_LOCATION_LIST";
export const CHANGE_CATEGORY_LIST = "CHANGE_CATEGORY_LIST";
export const CHANGE_LOCATION_LIST = "CHANGE_LOCATION_LIST";
export const GET_LOCATION = "GET_LOCATION";
export const GET_LISTING_BOX_CUSTOM = "GET_LISTING_BOX_CUSTOM";
export const GET_LISTING_BOX_CUSTOM_ALL = "GET_LISTING_BOX_CUSTOM_ALL";

export const GET_LISTING_DETAIL = "GET_LISTING_DETAIL";
export const RESET_LISTING_DETAIL = "RESET_LISTING_DETAIL";
export const GET_LISTING_DESTINATION = "GET_LISTING_DESTINATION";
export const GET_LISTING_DESTINATION_ALL = "GET_LISTING_DESTINATION_ALL";
export const GET_LISTING_LIST_FEATURE = "GET_LISTING_LIST_FEATURE";
export const GET_LISTING_LIST_FEATURE_ALL = "GET_LISTING_LIST_FEATURE_ALL";
export const GET_LISTING_PHOTOS = "GET_LISTING_PHOTOS";
export const GET_LISTING_PHOTOS_ALL = "GET_LISTING_PHOTOS_ALL";
export const GET_LISTING_REVIEWS = "GET_LISTING_REVIEWS";
export const GET_LISTING_REVIEWS_ALL = "GET_LISTING_REVIEWS_ALL";
export const GET_LISTING_EVENTS = "GET_LISTING_EVENTS";
export const GET_LISTING_EVENTS_ALL = "GET_LISTING_EVENTS_ALL";
export const GET_LISTING_VIDEOS = "GET_LISTING_VIDEOS";
export const GET_LISTING_VIDEOS_ALL = "GET_LISTING_VIDEOS_ALL";
export const GET_LISTING_DETAIL_NAV = "GET_LISTING_DETAIL_NAV";
export const CHANGE_LISTING_DETAIL_NAV = "CHANGE_LISTING_DETAIL_NAV";
export const GET_COMMENT_IN_REVIEWS = "GET_COMMENT_IN_REVIEWS";
export const GET_LISTING_SIDEBAR = "GET_LISTING_SIDEBAR";
export const GET_REPORT_FORM = "GET_REPORT_FORM";
export const GET_REPORT_MESSAGE = "GET_REPORT_MESSAGE";

export const GET_EVENTS = "GET_EVENTS";
export const GET_EVENT_DETAIL = "GET_EVENT_DETAIL";
export const GET_EVENTS_LOADMORE = "GET_EVENTS_LOADMORE";
export const GET_EVENT_DISCUSSION = "GET_EVENT_DISCUSSION";
export const GET_EVENT_DISCUSSION_LATEST = "GET_EVENT_DISCUSSION_LATEST";
export const GET_EVENT_DISCUSSION_LOADMORE = "GET_EVENT_DISCUSSION_LOADMORE";
export const GET_COMMENT_DISCUSSION_EVENT = "GET_COMMENT_DISCUSSION_EVENT";
export const GET_EVENT_SEARCH_RESULTS = "GET_EVENT_SEARCH_RESULTS";
export const GET_EVENT_SEARCH_RESULTS_LOADMORE =
  "GET_EVENT_SEARCH_RESULTS_LOADMORE";

export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_LOADMORE = "GET_ARTICLES_LOADMORE";
export const GET_ARTICLE_DETAIL = "GET_ARTICLE_DETAIL";

export const GET_PAGE = "GET_PAGE";
export const GET_SETTINGS = "GET_SETTINGS";

export const IS_POPUP_LOGIN = "IS_POPUP_LOGIN";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const CHECK_TOKEN = "CHECK_TOKEN";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const GET_MY_FAVORITES = "GET_MY_FAVORITES";
export const TOGGLE_MY_FAVORITES = "TOGGLE_MY_FAVORITES";
export const RESET_MY_FAVORITES = "RESET_MY_FAVORITES";
export const GET_MY_PROFILE = "GET_MY_PROFILE";
export const POST_MY_PROFILE = "POST_MY_PROFILE";
export const POST_MY_PROFILE_ERROR = "POST_MY_PROFILE_ERROR";
export const GET_SHORT_PROFILE = "GET_SHORT_PROFILE";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const ADD_LISTING_DETAIL_FAVORITES = "ADD_LISTING_DETAIL_FAVORITES";
export const GET_ACCOUNT_NAV = "GET_ACCOUNT_NAV";
export const GET_PROFILE_FORM = "GET_PROFILE_FORM";
export const GET_MY_LISTINGS = "GET_MY_LISTINGS";
export const GET_MY_LISTINGS_LOADMORE = "GET_MY_LISTINGS_LOADMORE";
export const GET_MY_LISTING_ERROR = "GET_MY_LISTING_ERROR";
export const GET_LISTING_STATUS = "GET_LISTING_STATUS";
export const GET_EVENT_STATUS = "GET_EVENT_STATUS";
export const GET_POST_TYPES = "GET_POST_TYPES";
export const GET_MY_EVENTS = "GET_MY_EVENTS";
export const GET_MY_EVENTS_LOADMORE = "GET_MY_EVENTS_LOADMORE";
export const GET_MY_EVENT_ERROR = "GET_MY_EVENT_ERROR";
export const GET_MY_NOTIFICATIONS = "GET_MY_NOTIFICATIONS";
export const GET_MY_NOTIFICATIONS_LOADMORE = "GET_MY_NOTIFICATIONS_LOADMORE";
export const GET_MY_NOTIFICATION_ERROR = "GET_MY_NOTIFICATION_ERROR";
export const DELETE_MY_NOTIFICATION = "DELETE_MY_NOTIFICATION";
export const DELETE_MY_NOTIFICATION_ERROR = "DELETE_MY_NOTIFICATION_ERROR";
export const GET_MESSAGE_LIST = "GET_MESSAGE_LIST";
export const GET_MESSAGE_CHAT = "GET_MESSAGE_CHAT";
export const GET_MESSAGE_CHAT_LOADMORE = "GET_MESSAGE_CHAT_LOADMORE";
export const PUT_MESSAGE_CHAT = "PUT_MESSAGE_CHAT";
export const PUT_MESSAGE_CHAT_LISTENER = "PUT_MESSAGE_CHAT_LISTENER";
export const DELETE_MESSAGE_CHAT = "DELETE_MESSAGE_CHAT";
export const EDIT_MESSAGE_CHAT = "EDIT_MESSAGE_CHAT";
export const RESET_MESSAGE_CHAT = "RESET_MESSAGE_CHAT";
export const WRITING_MESSAGE_CHAT = "WRITING_MESSAGE_CHAT";
export const GET_MESSAGE_NEW_COUNT = "GET_MESSAGE_NEW_COUNT";
export const GET_CURRENT_SEND_MESSAGE_SCREEN =
  "GET_CURRENT_SEND_MESSAGE_SCREEN";
export const GET_SIGNUP_FORM = "GET_SIGNUP_FORM";
export const SIGNUP = "SIGNUP";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_LOADING = "SIGNUP_LOADING";
export const GET_COUNT_MESSAGES = "GET_COUNT_MESSAGES";
export const GET_COUNT_NOTIFICATIONS = "GET_COUNT_NOTIFICATIONS";
export const GET_COUNT_NOTIFICATIONS_REALTIMEFAKER =
  "GET_COUNT_NOTIFICATIONS_REALTIMEFAKER";
export const SEARCH_USERS = "SEARCH_USERS";
export const SEARCH_USERS_ERROR = "SEARCH_USERS_ERROR";
export const GET_USER = "GET_USER";
export const GET_USERS_FROM_FIREBASE = "GET_USERS_FROM_FIREBASE";
export const GET_USERS_FROM_FIREBASE_LOADING =
  "GET_USERS_FROM_FIREBASE_LOADING";
export const GET_USERS_FROM_FIREBASE_ERROR = "GET_USERS_FROM_FIREBASE_ERROR";
export const GET_KEY_FIREBASE = "GET_KEY_FIREBASE";
export const GET_KEY_FIREBASE2 = "GET_KEY_FIREBASE2";
export const USER_CONNECTION = "USER_CONNECTION";
export const POST_USER_CONNECTION = "POST_USER_CONNECTION";
export const GET_DEVICE_TOKEN = "GET_DEVICE_TOKEN";
export const GET_NOTIFICATION_SETTING = "GET_NOTIFICATION_SETTING";
export const SET_NOTIFICATION_SETTING = "SET_NOTIFICATION_SETTING";
export const GET_NOTIFICATION_ADMIN_SETTING = "GET_NOTIFICATION_ADMIN_SETTING";
export const GET_REVIEW_FIELDS = "GET_REVIEW_FIELDS";
